[package]
name = "tinystr"
description = """
A small ASCII-only bounded length string representation.
"""
version = "0.3.0"
authors = ["Raph Levien <raph.levien@gmail.com>", "Zibi Braniecki <zibi@braniecki.net>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/zbraniecki/tinystr"
readme = "README.md"
keywords = ["string", "str", "small", "tiny"]
categories = ["data-structures"]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "tinystr"
harness = false